### ISSUE TITLE
[BUG]: 无法显示隧道

### ISSUE THREAD

**Issue by BLUE-POISON096** [Muska-Ami/NyaLCF#172]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

无法显示隧道

### 版本

0.2.0

### 运行日志

```sh
[2024-07-26 20:19:48.209187][INFO]: Checking update...
[2024-07-26 20:19:48.212214][INFO]: Instance "GetMaterialController" has been created
[2024-07-26 20:19:48.213214][INFO]: Instance "GetMaterialController" has been initialized
[2024-07-26 20:19:48.213214][INFO]: Instance "HC" has been created
[2024-07-26 20:19:48.213214][INFO]: Instance "HC" has been initialized
[2024-07-26 20:19:48.213214][INFO]: Instance "FrpcController" has been created
[2024-07-26 20:19:48.213214][INFO]: Instance "FrpcController" has been initialized
[2024-07-26 20:19:48.214214][INFO]: Instance "ConsoleController" has been created
[2024-07-26 20:19:48.214214][INFO]: Instance "ConsoleController" has been initialized
[2024-07-26 20:19:48.214214][INFO]: Instance "UserController" has been created
[2024-07-26 20:19:48.214214][INFO]: Instance "UserController" has been initialized
[2024-07-26 20:19:48.230196][INFO]: Check token if is valid
[2024-07-26 20:19:49.297805][INFO]: You are running latest version.
[2024-07-26 20:19:49.395419][INFO]: Refresh user info
[2024-07-26 20:19:49.582915][INFO]: Auto updating proxies list...
[2024-07-26 20:19:49.593794][INFO]: Instance "DPanelController" has been created
[2024-07-26 20:19:49.594790][INFO]: Instance "DPanelController" has been initialized
[2024-07-26 20:19:49.594790][INFO]: Get broadcast announcement
[2024-07-26 20:19:49.617360][INFO]: Auto sign successfully.
[2024-07-26 20:19:49.740142][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[2024-07-26 20:19:49.740142][WARN]: Can not update proxies list widgets, request failed.
[2024-07-26 20:19:49.741171][WARN]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[2024-07-26 20:19:49.759341][INFO]: Get common announcement
[2024-07-26 20:20:00.462366][INFO]: Instance "FrpcSettingController" has been created
[2024-07-26 20:20:00.463366][INFO]: Instance "FrpcSettingController" has been initialized
[2024-07-26 20:20:00.463366][INFO]: Instance "DSettingLauncherController" has been created
[2024-07-26 20:20:00.464367][INFO]: Instance "DSettingLauncherController" has been initialized
[2024-07-26 20:20:00.464367][INFO]: Build windows platform arch list
[2024-07-26 20:20:11.234811][INFO]: Instance "ProxiesController" has been created
[2024-07-26 20:20:11.234811][INFO]: Instance "ProxiesController" has been initialized
[2024-07-26 20:20:11.361324][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[2024-07-26 20:20:13.633589][INFO]: OPEN DIALOG 707442148
[2024-07-26 20:20:14.817345][INFO]: Killing all process
[2024-07-26 20:20:14.818348][INFO]: All process killed
[2024-07-26 20:22:20.662419][INFO]: Checking update...
[2024-07-26 20:22:20.665419][INFO]: Instance "GetMaterialController" has been created
[2024-07-26 20:22:20.665419][INFO]: Instance "GetMaterialController" has been initialized
[2024-07-26 20:22:20.666927][INFO]: Instance "HC" has been created
[2024-07-26 20:22:20.666927][INFO]: Instance "HC" has been initialized
[2024-07-26 20:22:20.666927][INFO]: Instance "FrpcController" has been created
[2024-07-26 20:22:20.666927][INFO]: Instance "FrpcController" has been initialized
[2024-07-26 20:22:20.666927][INFO]: Instance "ConsoleController" has been created
[2024-07-26 20:22:20.666927][INFO]: Instance "ConsoleController" has been initialized
[2024-07-26 20:22:20.667972][INFO]: Instance "UserController" has been created
[2024-07-26 20:22:20.668240][INFO]: Instance "UserController" has been initialized
[2024-07-26 20:22:20.684807][INFO]: Check token if is valid
[2024-07-26 20:22:20.802110][INFO]: Already signed, skip auto sign action.
[2024-07-26 20:22:20.809225][INFO]: Refresh user info
[2024-07-26 20:22:20.935702][INFO]: Auto updating proxies list...
[2024-07-26 20:22:20.967340][INFO]: Instance "DPanelController" has been created
[2024-07-26 20:22:20.967340][INFO]: Instance "DPanelController" has been initialized
[2024-07-26 20:22:20.968345][INFO]: Get broadcast announcement
[2024-07-26 20:22:21.077536][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[2024-07-26 20:22:21.077536][WARN]: Can not update proxies list widgets, request failed.
[2024-07-26 20:22:21.077536][WARN]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[2024-07-26 20:22:21.083654][INFO]: Get common announcement
[2024-07-26 20:22:21.479732][INFO]: You are running latest version.
[2024-07-26 20:22:51.380326][INFO]: Instance "ProxiesController" has been created
[2024-07-26 20:22:51.381326][INFO]: Instance "ProxiesController" has been initialized
[2024-07-26 20:22:51.515692][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[2024-07-26 20:22:52.798906][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[2024-07-26 20:23:00.461306][INFO]: Killing all process
[2024-07-26 20:23:00.462306][INFO]: All process killed
[2024-07-26 20:23:03.702520][INFO]: OPEN DIALOG 831161329
[2024-07-26 20:23:06.060361][INFO]: CLOSE DIALOG 831161329
[2024-07-26 20:23:07.821846][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[2024-07-26 20:23:10.420766][INFO]: Get broadcast announcement
[2024-07-26 20:23:10.538631][INFO]: Get common announcement
[2024-07-26 20:23:23.066191][INFO]: Instance "FrpcSettingController" has been created
[2024-07-26 20:23:23.066191][INFO]: Instance "FrpcSettingController" has been initialized
[2024-07-26 20:23:23.066191][INFO]: Instance "DSettingLauncherController" has been created
[2024-07-26 20:23:23.067111][INFO]: Instance "DSettingLauncherController" has been initialized
[2024-07-26 20:23:23.067111][INFO]: Build windows platform arch list
```

**Comment by Muska-Ami** [comment]
你都没有隧道怎么显示（

**Comment by Muska-Ami** [comment]
请认真填写Issue标题，这对开发者来说更容易明白该Issue关于什么

**Comment by Muska-Ami** [comment]
长时间未回复，Closed.
