### ISSUE TITLE
[BUG]: 连接失败

### ISSUE THREAD

**Issue by ZWlovelife** [Muska-Ami/NyaLCF#174]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

可以 ping 通 api-v2.locyanfrp.cn，debug 模式下可以成功获取账户信息，但连接失败。
![image](https://github.com/user-attachments/assets/f9da93ba-d882-414b-9816-04d3454b9621)

### 版本

软件版本：0.2.0 (+2)

### 运行日志

```sh
[ERROR]: DioException [connection error]: The connection errored: Failed host lookup: 'api-v2.locyanfrp.cn' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'api-v2.locyanfrp.cn' (OS Error: 不知道这样的主机。
, errno = 11001)
Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[WARN]: Can not update proxies list widgets, request failed.
[WARN]: DioException [connection error]: The connection errored: Failed host lookup: 'api-v2.locyanfrp.cn' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'api-v2.locyanfrp.cn' (OS Error: 不知道这样的主机。
, errno = 11001)

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 502 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 502 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[WARN]: Can not update proxies list widgets, request failed.
[WARN]: DioException [bad response]: This exception was thrown because the response has a status code of 502 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 502 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
[WARN]: Check user token success but refresh user info failed. User info may not the latest!

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 500 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      UserAuth.getInfo (package:nyalcf_core/network/dio/auth/user_auth.dart:54)
<asynchronous suspension>
#2      HC.load.<anonymous closure> (package:nyalcf_ui/views/home.dart:101)
<asynchronous suspension>
#3      HC.load (package:nyalcf_ui/views/home.dart:101)
<asynchronous suspension>

[WARN]: Check user token success but refresh user info failed. User info may not the latest!

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>


[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      OtherSign.checkSign (package:nyalcf_core/network/dio/other/sign_other.dart:27)
<asynchronous suspension>
#2      PanelHome.build.<anonymous closure> (package:nyalcf_ui/views/panel/home.dart:97)
<asynchronous suspension>

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:25)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>
```

**Comment by Muska-Ami** [comment]
重新登录试试

**Comment by ltzXiaoYanMo** [comment]
```bash
curl 4.ipw.cn

```
看看IP，感觉像被拦了

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 它这个403不像是被拦了

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 被拦了应该是400

**Comment by ltzXiaoYanMo** [comment]
拿它的IP去看看API日志吧

**Comment by Muska-Ami** [comment]
可以的话请贴出完整日志，请不要手动帮我们提取日志

**Comment by autumn-moon-py** [comment]
确认重新登录能解决此问题

**Comment by ZWlovelife** [comment]
确认重新登录能解决此问题。
