### ISSUE TITLE
[FEAT]: 清理被删除的隧道的配置文件

### ISSUE THREAD

**Issue by Suisuroru** [Muska-Ami/NyaLCF#179]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

%Roaming%\moe.muska.ami\nyanana\frpc\proxies目录下，已经被删除的隧道仍然保存配置文件，且相关自动启动参数也仍然保存

希望能在检查到隧道删除时自动删除相关配置文件和自动启动参数

**Comment by Suisuroru** [comment]
由于这个情况的存在，每次启动软件的时候都会导致其尝试去启动已经被删除的隧道，显而易见，这会是失败的，这就会降低软件启动的效率

**Comment by Suisuroru** [comment]
这是我测试时的frpc日志

[2024-08-25 09:49:21.240291][FPRC][INFO]: [81395] 2024/08/25 09:49:21 [I] [root.go:118] 欢迎使用LoCyanFrp, Stable Version: v0.51.3 - #2024021801
[2024-08-25 09:49:21.241306][FPRC][INFO]: [81398] 2024/08/25 09:49:21 [I] [root.go:118] 欢迎使用LoCyanFrp, Stable Version: v0.51.3 - #2024021801
[2024-08-25 09:49:21.636145][FPRC][INFO]: [81398] 2024/08/25 09:49:21 [I] [service.go:301] [5d5adacb085470d4d13d085bc048dba9-366b6dd87c972b57] 成功登录至服务器, 获取到RunID [5d5adacb085470d4d13d085bc048dba9-366b6dd87c972b57]
[2024-08-25 09:49:21.636145][FPRC][INFO]: [81398] 2024/08/25 09:49:21 [I] [proxy_manager.go:150] [5d5adacb085470d4d13d085bc048dba9-366b6dd87c972b57] 添加隧道: [5d5adacb085470d4d13d085bc048dba9.32432432433]
[2024-08-25 09:49:22.172106][FPRC][INFO]: [81398] 2024/08/25 09:49:22 [I] [control.go:177] [5d5adacb085470d4d13d085bc048dba9-366b6dd87c972b57] [5d5adacb085470d4d13d085bc048dba9.32432432433] 映射启动成功, 感谢您使用LCF!
[2024-08-25 09:49:22.172106][FPRC][INFO]: [81398] 2024/08/25 09:49:22 [I] [control.go:178] [5d5adacb085470d4d13d085bc048dba9-366b6dd87c972b57] 你可以使用 [47.97.49.128:39023] 连接至您的隧道: 5d5adacb085470d4d13d085bc048dba9.32432432433
[2024-08-25 09:49:23.991706][FPRC][INFO]: [81395] 2024/08/25 09:49:23 [I] [service.go:301] [5d5adacb085470d4d13d085bc048dba9-588c24f66cfe8c2a] 成功登录至服务器, 获取到RunID [5d5adacb085470d4d13d085bc048dba9-588c24f66cfe8c2a]
[2024-08-25 09:49:23.991706][FPRC][INFO]: [81395] 2024/08/25 09:49:23 [I] [proxy_manager.go:150] [5d5adacb085470d4d13d085bc048dba9-588c24f66cfe8c2a] 添加隧道: [5d5adacb085470d4d13d085bc048dba9.5553]
[2024-08-25 09:49:26.243056][FPRC][WARN]: [81395] 2024/08/25 09:49:26 [W] [control.go:170] [5d5adacb085470d4d13d085bc048dba9-588c24f66cfe8c2a] [5d5adacb085470d4d13d085bc048dba9.5553] 启动失败: LoCyanFrp API Error (Status: 404, Text: 404 Proxy not found)
[2024-08-25 09:53:17.058901][FPRC][INFO]: [81398] 2024/08/25 09:53:17 [I] [root.go:118] 欢迎使用LoCyanFrp, Stable Version: v0.51.3 - #2024021801
[2024-08-25 09:53:24.907757][FPRC][INFO]: [81398] 2024/08/25 09:53:24 [I] [service.go:301] [5d5adacb085470d4d13d085bc048dba9-913bf3909973c2aa] 成功登录至服务器, 获取到RunID [5d5adacb085470d4d13d085bc048dba9-913bf3909973c2aa]
[2024-08-25 09:53:24.908261][FPRC][INFO]: [81398] 2024/08/25 09:53:24 [I] [proxy_manager.go:150] [5d5adacb085470d4d13d085bc048dba9-913bf3909973c2aa] 添加隧道: [5d5adacb085470d4d13d085bc048dba9.3243243243]
[2024-08-25 09:53:30.599854][FPRC][INFO]: [81398] 2024/08/25 09:53:30 [I] [control.go:177] [5d5adacb085470d4d13d085bc048dba9-913bf3909973c2aa] [5d5adacb085470d4d13d085bc048dba9.3243243243] 映射启动成功, 感谢您使用LCF!
[2024-08-25 09:53:30.600394][FPRC][INFO]: [81398] 2024/08/25 09:53:30 [I] [control.go:178] [5d5adacb085470d4d13d085bc048dba9-913bf3909973c2aa] 你可以使用 [jp-3.lcf.1l1.icu:33976] 连接至您的隧道: 5d5adacb085470d4d13d085bc048dba9.3243243243

**Comment by Suisuroru** [comment]
这是Nya的日志

[2024-08-25 09:48:22.896817][INFO]: Checking update...
[2024-08-25 09:48:22.898328][INFO]: Instance "GetMaterialController" has been created
[2024-08-25 09:48:22.898328][INFO]: Instance "GetMaterialController" has been initialized
[2024-08-25 09:48:22.898328][INFO]: Instance "HC" has been created
[2024-08-25 09:48:22.898328][INFO]: Instance "HC" has been initialized
[2024-08-25 09:48:22.898328][INFO]: Instance "FrpcController" has been created
[2024-08-25 09:48:22.899327][INFO]: Instance "FrpcController" has been initialized
[2024-08-25 09:48:22.899327][INFO]: Instance "ConsoleController" has been created
[2024-08-25 09:48:22.899327][INFO]: Instance "ConsoleController" has been initialized
[2024-08-25 09:48:22.899327][INFO]: Instance "UserController" has been created
[2024-08-25 09:48:22.900334][INFO]: Instance "UserController" has been initialized
[2024-08-25 09:48:22.909327][INFO]: Check token if is valid
[2024-08-25 09:48:23.041103][INFO]: Refresh user info
[2024-08-25 09:48:23.122684][INFO]: Auto updating proxies list...
[2024-08-25 09:48:23.131742][INFO]: Instance "DPanelController" has been created
[2024-08-25 09:48:23.131742][INFO]: Instance "DPanelController" has been initialized
[2024-08-25 09:48:23.131742][INFO]: Get broadcast announcement
[2024-08-25 09:48:23.131742][INFO]: Starting proxy: 81395
[2024-08-25 09:48:23.239843][INFO]: Get common announcement
[2024-08-25 09:48:23.263702][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:28)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[2024-08-25 09:48:23.264724][WARN]: Can not update proxies list widgets, request failed.
[2024-08-25 09:48:23.264724][WARN]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[2024-08-25 09:48:23.613855][INFO]: You are running latest version.
[2024-08-25 09:48:25.018080][INFO]: Instance "ProxiesController" has been created
[2024-08-25 09:48:25.018080][INFO]: Instance "ProxiesController" has been initialized
[2024-08-25 09:48:25.094909][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:28)
<asynchronous suspension>
#2      ProxiesController.load (package:nyalcf_ui/controllers/proxies_controller.dart:333)
<asynchronous suspension>

[2024-08-25 09:49:09.842686][INFO]: OPEN DIALOG 909785064
[2024-08-25 09:49:10.865278][INFO]: Killing all process
[2024-08-25 09:49:10.866488][INFO]: Killing frpc process, pid: 30292
[2024-08-25 09:49:10.866488][INFO]: All process killed
[2024-08-25 09:49:20.966262][INFO]: Checking update...
[2024-08-25 09:49:20.967267][INFO]: Instance "GetMaterialController" has been created
[2024-08-25 09:49:20.967267][INFO]: Instance "GetMaterialController" has been initialized
[2024-08-25 09:49:20.968267][INFO]: Instance "HC" has been created
[2024-08-25 09:49:20.968267][INFO]: Instance "HC" has been initialized
[2024-08-25 09:49:20.968267][INFO]: Instance "FrpcController" has been created
[2024-08-25 09:49:20.968267][INFO]: Instance "FrpcController" has been initialized
[2024-08-25 09:49:20.968267][INFO]: Instance "ConsoleController" has been created
[2024-08-25 09:49:20.968267][INFO]: Instance "ConsoleController" has been initialized
[2024-08-25 09:49:20.968267][INFO]: Instance "UserController" has been created
[2024-08-25 09:49:20.968267][INFO]: Instance "UserController" has been initialized
[2024-08-25 09:49:20.978336][INFO]: Check token if is valid
[2024-08-25 09:49:21.107789][INFO]: Refresh user info
[2024-08-25 09:49:21.184429][INFO]: Auto updating proxies list...
[2024-08-25 09:49:21.185822][INFO]: Starting proxy: 81395
[2024-08-25 09:49:21.186327][INFO]: Starting proxy: 81398
[2024-08-25 09:49:21.192934][INFO]: Instance "DPanelController" has been created
[2024-08-25 09:49:21.192934][INFO]: Instance "DPanelController" has been initialized
[2024-08-25 09:49:21.192934][INFO]: Get broadcast announcement
[2024-08-25 09:49:21.314392][INFO]: Get common announcement
[2024-08-25 09:49:21.328877][WARN]: Can not update proxies list widgets, maybe it is not serialized yet.
[2024-08-25 09:49:21.663339][INFO]: You are running latest version.
[2024-08-25 09:49:25.554354][INFO]: OPEN DIALOG 834533136
[2024-08-25 09:49:26.434184][INFO]: CLOSE DIALOG 834533136
[2024-08-25 09:49:27.305799][INFO]: OPEN DIALOG 359404673
[2024-08-25 09:49:27.843864][INFO]: CLOSE DIALOG 359404673
[2024-08-25 09:49:31.524210][INFO]: Get broadcast announcement
[2024-08-25 09:49:31.635742][INFO]: Get common announcement
[2024-08-25 09:49:33.092817][INFO]: Instance "ProxiesController" has been created
[2024-08-25 09:49:33.092817][INFO]: Instance "ProxiesController" has been initialized
[2024-08-25 09:49:40.009434][INFO]: OPEN DIALOG 491282469
[2024-08-25 09:49:40.154659][INFO]: Successfully get config ini
[2024-08-25 09:49:40.154659][INFO]: CLOSE DIALOG 491282469
[2024-08-25 09:49:40.154659][INFO]: OPEN DIALOG 103821226
[2024-08-25 09:49:42.289868][INFO]: CLOSE DIALOG 103821226
[2024-08-25 09:49:43.129575][INFO]: OPEN DIALOG 726060900
[2024-08-25 09:49:43.219869][INFO]: Successfully get config ini
[2024-08-25 09:49:43.219869][INFO]: CLOSE DIALOG 726060900
[2024-08-25 09:49:43.219869][INFO]: OPEN DIALOG 553813545
[2024-08-25 09:49:44.258488][INFO]: CLOSE DIALOG 553813545
[2024-08-25 09:52:52.603947][INFO]: OPEN DIALOG 201556897
[2024-08-25 09:52:53.641019][INFO]: Killing all process
[2024-08-25 09:52:53.642020][INFO]: Killing frpc process, pid: 10036
[2024-08-25 09:52:53.642020][INFO]: All process killed
[2024-08-25 09:53:16.559315][INFO]: Checking update...
[2024-08-25 09:53:16.561785][INFO]: Instance "GetMaterialController" has been created
[2024-08-25 09:53:16.561785][INFO]: Instance "GetMaterialController" has been initialized
[2024-08-25 09:53:16.561785][INFO]: Instance "HC" has been created
[2024-08-25 09:53:16.561785][INFO]: Instance "HC" has been initialized
[2024-08-25 09:53:16.561785][INFO]: Instance "FrpcController" has been created
[2024-08-25 09:53:16.561785][INFO]: Instance "FrpcController" has been initialized
[2024-08-25 09:53:16.561785][INFO]: Instance "ConsoleController" has been created
[2024-08-25 09:53:16.561785][INFO]: Instance "ConsoleController" has been initialized
[2024-08-25 09:53:16.561785][INFO]: Instance "UserController" has been created
[2024-08-25 09:53:16.561785][INFO]: Instance "UserController" has been initialized
[2024-08-25 09:53:16.573279][INFO]: Check token if is valid
[2024-08-25 09:53:16.925439][INFO]: Refresh user info
[2024-08-25 09:53:17.011170][INFO]: Auto updating proxies list...
[2024-08-25 09:53:17.012170][INFO]: Starting proxy: 81398
[2024-08-25 09:53:17.021171][INFO]: Instance "DPanelController" has been created
[2024-08-25 09:53:17.022171][INFO]: Instance "DPanelController" has been initialized
[2024-08-25 09:53:17.022171][INFO]: Get broadcast announcement
[2024-08-25 09:53:17.147785][WARN]: Can not update proxies list widgets, maybe it is not serialized yet.
[2024-08-25 09:53:17.506479][INFO]: Get common announcement
[2024-08-25 09:53:17.693661][INFO]: You are running latest version.
[2024-08-25 09:53:47.153347][INFO]: Instance "ProxiesController" has been created
[2024-08-25 09:53:47.154329][INFO]: Instance "ProxiesController" has been initialized
[2024-08-25 09:53:57.153431][INFO]: OPEN DIALOG 304840248
[2024-08-25 09:55:30.032857][INFO]: CLOSE DIALOG 304840248
[2024-08-25 09:55:31.882471][INFO]: OPEN DIALOG 925033129
[2024-08-25 09:55:32.578101][INFO]: Killing all process
[2024-08-25 09:55:32.578101][INFO]: Killing frpc process, pid: 10604
[2024-08-25 09:55:32.578101][INFO]: All process killed
[2024-08-25 10:02:14.893054][INFO]: Checking update...
[2024-08-25 10:02:14.895059][INFO]: Instance "GetMaterialController" has been created
[2024-08-25 10:02:14.895059][INFO]: Instance "GetMaterialController" has been initialized
[2024-08-25 10:02:14.895059][INFO]: Instance "HC" has been created
[2024-08-25 10:02:14.895059][INFO]: Instance "HC" has been initialized
[2024-08-25 10:02:14.895059][INFO]: Instance "FrpcController" has been created
[2024-08-25 10:02:14.896058][INFO]: Instance "FrpcController" has been initialized
[2024-08-25 10:02:14.896058][INFO]: Instance "ConsoleController" has been created
[2024-08-25 10:02:14.896058][INFO]: Instance "ConsoleController" has been initialized
[2024-08-25 10:02:14.896058][INFO]: Instance "UserController" has been created
[2024-08-25 10:02:14.896058][INFO]: Instance "UserController" has been initialized
[2024-08-25 10:02:14.905403][INFO]: Check token if is valid
[2024-08-25 10:02:15.280895][INFO]: Refresh user info
[2024-08-25 10:02:15.365043][INFO]: Auto updating proxies list...
[2024-08-25 10:02:15.377043][INFO]: Instance "DPanelController" has been created
[2024-08-25 10:02:15.378042][INFO]: Instance "DPanelController" has been initialized
[2024-08-25 10:02:15.378042][INFO]: Get broadcast announcement
[2024-08-25 10:02:15.500114][ERROR]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Trace:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      ProxiesGet.get (package:nyalcf_core/network/dio/proxies/get_proxies.dart:28)
<asynchronous suspension>
#2      ProxiesGetter.startUp (package:nyalcf_core_extend/utils/proxies_getter.dart:16)
<asynchronous suspension>

[2024-08-25 10:02:15.500114][WARN]: Can not update proxies list widgets, request failed.
[2024-08-25 10:02:15.500114][WARN]: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[2024-08-25 10:02:15.994916][INFO]: Get common announcement
[2024-08-25 10:02:16.134891][INFO]: You are running latest version.
[2024-08-25 10:02:29.194337][INFO]: OPEN DIALOG 579163920
[2024-08-25 10:02:32.305407][INFO]: Killing all process
[2024-08-25 10:02:32.305407][INFO]: All process killed

**Comment by Muska-Ami** [comment]
会尽快实现相关功能，但不会移除已删除隧道的配置文件。会将其移动到临时目录，由用户决定是否删除。
自动启动项目则会直接移除。

**Comment by Muska-Ami** [comment]
Update: 应该提供一个已存储的配置文件管理界面，不必移动位置

**Comment by Suisuroru** [comment]
即使如此，那也应当将删除的隧道的自动启动列表删除以提高效率
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月5日(星期四) 晚上7:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Muska-Ami/NyaLCF] [FEAT]: 清理被删除的隧道的配置文件 (Issue #179)














 
Update: 应该提供一个已存储的配置文件管理界面，不必移动位置

**Comment by Muska-Ami** [comment]
这个会实现，不过配置不会自动删除

**Comment by Muska-Ami** [comment]
由于我个人精力有限，可能不会那么快发布更新
启动的效率其实是不差的，因为自动启动隧道是异步操作，只会有轻微的性能影响

**Comment by Muska-Ami** [comment]
已完成
