### ISSUE TITLE
“查看进程列表”在Releases构建输出中灰屏

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#2]
可能由于动态刷新值问题导致，目前打开此界面灰屏可以通过按下 `Esc` 键退出

**Comment by Muska-Ami** [comment]
确认由于Get组件使用不当导致
```shell
flutter:       [Get] the improper use of a GetX has been detected.
flutter:       You should only use GetX or Obx for the specific widget that will be updated.
flutter:       If you are seeing this error, you probably did not insert any observable variables into GetX/Obx
flutter:       or insert them outside the scope that GetX considers suitable for an update
flutter:       (example: GetX => HeavyWidget => variableObservable).
flutter:       If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.
flutter:
flutter: #0      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:29)
flutter: #1      ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:56)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
flutter: #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #83     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #96     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
```

**Comment by Muska-Ami** [comment]
已修复

**Comment by ltzXiaoYanMo** [comment]
byd自言自语是罢（
