### ISSUE TITLE
[BUG]: 当账户的流量为无限时，无法完成授权登陆

### ISSUE THREAD

**Issue by Suisuroru** [Muska-Ami/NyaLCF#220]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

点击授权按钮后会跳转至
http://localhost:5173/auth/oauth/authorize?app_id=1&scopes=User,Proxy,Sign&redirect_url=http://localhost:21131/oauth/callback):5173/auth/oauth/authorize?app_id=1&scopes=User,Proxy,Sign&redirect_url=http://localhost:21131/oauth/callback
我并不知道这是否是正常的地址（我并不知道是否使用了本地服务器验证），但跳转后会提示此页面无法完成验证
![image](https://github.com/user-attachments/assets/1e2af03c-287c-4188-ad63-1d1cdbdfd72f)

### 版本

1.0.0(+1)

### 运行日志

```sh
[2024-12-23 16:12:14.640195][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:12:14.640195][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:12:14.641199][INFO]: Instance "HomeController" has been created
[2024-12-23 16:12:14.641199][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:12:14.642200][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:12:14.642200][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:12:14.642200][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:12:14.643199][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:12:14.643199][INFO]: Instance "UserController" has been created
[2024-12-23 16:12:14.644368][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:12:16.213390][INFO]: Instance "_Controller" has been created
[2024-12-23 16:12:16.216395][INFO]: Instance "_Controller" has been initialized
[2024-12-23 16:12:58.071202][INFO]: OPEN DIALOG 760314201
[2024-12-23 16:13:00.271429][INFO]: Killing all process
[2024-12-23 16:13:00.272430][INFO]: All process killed
[2024-12-23 16:13:16.553268][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:13:16.553772][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:13:16.554776][INFO]: Instance "HomeController" has been created
[2024-12-23 16:13:16.554776][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:13:16.555776][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:13:16.556775][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:13:16.556775][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:13:16.557775][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:13:16.558775][INFO]: Instance "UserController" has been created
[2024-12-23 16:13:16.558775][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:13:17.853494][INFO]: Instance "_Controller" has been created
[2024-12-23 16:13:17.856017][INFO]: Instance "_Controller" has been initialized
[2024-12-23 16:13:23.578988][INFO]: Instance "FrpcSettingController" has been created
[2024-12-23 16:13:23.581989][INFO]: Instance "FrpcSettingController" has been initialized
[2024-12-23 16:13:23.581989][INFO]: Instance "LauncherSettingLauncherController" has been created
[2024-12-23 16:13:23.583494][INFO]: Instance "LauncherSettingLauncherController" has been initialized
[2024-12-23 16:13:23.584501][INFO]: 
=== [DATA START] ===
[]
=== [DATA END] ===
[2024-12-23 16:13:23.584501][INFO]: Build windows platform arch list
[2024-12-23 16:14:12.884287][INFO]: 
=== [DATA START] ===
[]
=== [DATA END] ===
[2024-12-23 16:14:12.884287][INFO]: Build windows platform arch list
[2024-12-23 16:14:26.375627][INFO]: Selected arch: amd64
[2024-12-23 16:14:26.960529][INFO]: OPEN DIALOG 229980335
[2024-12-23 16:14:38.336630][INFO]: CLOSE DIALOG 229980335
[2024-12-23 16:14:38.338630][INFO]: 
=== [DATA START] ===
[
  "0.51.3-6"
]
=== [DATA END] ===
[2024-12-23 16:14:38.338630][INFO]: Build windows platform arch list
[2024-12-23 16:15:37.043593][INFO]: OPEN DIALOG 280763286
[2024-12-23 16:15:37.866903][INFO]: Killing all process
[2024-12-23 16:15:37.873608][INFO]: All process killed
[2024-12-23 16:15:54.810919][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:15:54.812426][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:15:54.813460][INFO]: Instance "HomeController" has been created
[2024-12-23 16:15:54.814433][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:15:54.814433][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:15:54.815431][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:15:54.816432][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:15:54.816432][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:15:54.817432][INFO]: Instance "UserController" has been created
[2024-12-23 16:15:54.817432][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:15:56.078203][INFO]: Instance "_Controller" has been created
[2024-12-23 16:15:56.088250][INFO]: Instance "_Controller" has been initialized
```

**Comment by Suisuroru** [comment]
我未注意到维护时间，维护后再看看是否存在

**Comment by Suisuroru** [comment]
今天仍然有这个问题，感觉是跳转页面地址不正确（

**Comment by Muska-Ami** [comment]
你应该更新到v1.0.0+3

**Comment by Suisuroru** [comment]
这是否是意料之外的情况（
![image](https://github.com/user-attachments/assets/70d3877a-251e-46ef-8529-ddd47bdb592a)

**Comment by Suisuroru** [comment]
[2024-12-23 16:12:14.640195][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:12:14.640195][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:12:14.641199][INFO]: Instance "HomeController" has been created
[2024-12-23 16:12:14.641199][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:12:14.642200][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:12:14.642200][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:12:14.642200][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:12:14.643199][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:12:14.643199][INFO]: Instance "UserController" has been created
[2024-12-23 16:12:14.644368][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:12:16.213390][INFO]: Instance "_Controller" has been created
[2024-12-23 16:12:16.216395][INFO]: Instance "_Controller" has been initialized
[2024-12-23 16:12:58.071202][INFO]: OPEN DIALOG 760314201
[2024-12-23 16:13:00.271429][INFO]: Killing all process
[2024-12-23 16:13:00.272430][INFO]: All process killed
[2024-12-23 16:13:16.553268][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:13:16.553772][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:13:16.554776][INFO]: Instance "HomeController" has been created
[2024-12-23 16:13:16.554776][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:13:16.555776][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:13:16.556775][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:13:16.556775][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:13:16.557775][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:13:16.558775][INFO]: Instance "UserController" has been created
[2024-12-23 16:13:16.558775][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:13:17.853494][INFO]: Instance "_Controller" has been created
[2024-12-23 16:13:17.856017][INFO]: Instance "_Controller" has been initialized
[2024-12-23 16:13:23.578988][INFO]: Instance "FrpcSettingController" has been created
[2024-12-23 16:13:23.581989][INFO]: Instance "FrpcSettingController" has been initialized
[2024-12-23 16:13:23.581989][INFO]: Instance "LauncherSettingLauncherController" has been created
[2024-12-23 16:13:23.583494][INFO]: Instance "LauncherSettingLauncherController" has been initialized
[2024-12-23 16:13:23.584501][INFO]: 
=== [DATA START] ===
[]
=== [DATA END] ===
[2024-12-23 16:13:23.584501][INFO]: Build windows platform arch list
[2024-12-23 16:14:12.884287][INFO]: 
=== [DATA START] ===
[]
=== [DATA END] ===
[2024-12-23 16:14:12.884287][INFO]: Build windows platform arch list
[2024-12-23 16:14:26.375627][INFO]: Selected arch: amd64
[2024-12-23 16:14:26.960529][INFO]: OPEN DIALOG 229980335
[2024-12-23 16:14:38.336630][INFO]: CLOSE DIALOG 229980335
[2024-12-23 16:14:38.338630][INFO]: 
=== [DATA START] ===
[
  "0.51.3-6"
]
=== [DATA END] ===
[2024-12-23 16:14:38.338630][INFO]: Build windows platform arch list
[2024-12-23 16:15:37.043593][INFO]: OPEN DIALOG 280763286
[2024-12-23 16:15:37.866903][INFO]: Killing all process
[2024-12-23 16:15:37.873608][INFO]: All process killed
[2024-12-23 16:15:54.810919][INFO]: Instance "GetMaterialController" has been created
[2024-12-23 16:15:54.812426][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-23 16:15:54.813460][INFO]: Instance "HomeController" has been created
[2024-12-23 16:15:54.814433][INFO]: Instance "HomeController" has been initialized
[2024-12-23 16:15:54.814433][INFO]: Instance "FrpcController" has been created
[2024-12-23 16:15:54.815431][INFO]: Instance "FrpcController" has been initialized
[2024-12-23 16:15:54.816432][INFO]: Instance "ConsoleController" has been created
[2024-12-23 16:15:54.816432][INFO]: Instance "ConsoleController" has been initialized
[2024-12-23 16:15:54.817432][INFO]: Instance "UserController" has been created
[2024-12-23 16:15:54.817432][INFO]: Instance "UserController" has been initialized
[2024-12-23 16:15:56.078203][INFO]: Instance "_Controller" has been created
[2024-12-23 16:15:56.088250][INFO]: Instance "_Controller" has been initialized
[2024-12-23 16:24:36.118071][INFO]: OPEN DIALOG 811042637
[2024-12-23 16:24:36.991495][INFO]: Killing all process
[2024-12-23 16:24:36.993521][INFO]: All process killed
[2024-12-27 15:54:35.189934][INFO]: Instance "GetMaterialController" has been created
[2024-12-27 15:54:35.190938][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-27 15:54:35.191936][INFO]: Instance "HomeController" has been created
[2024-12-27 15:54:35.192934][INFO]: Instance "HomeController" has been initialized
[2024-12-27 15:54:35.192934][INFO]: Instance "FrpcController" has been created
[2024-12-27 15:54:35.193932][INFO]: Instance "FrpcController" has been initialized
[2024-12-27 15:54:35.194932][INFO]: Instance "ConsoleController" has been created
[2024-12-27 15:54:35.195933][INFO]: Instance "ConsoleController" has been initialized
[2024-12-27 15:54:35.195933][INFO]: Instance "UserController" has been created
[2024-12-27 15:54:35.196934][INFO]: Instance "UserController" has been initialized
[2024-12-27 15:54:37.129865][INFO]: Instance "_Controller" has been created
[2024-12-27 15:54:37.130862][INFO]: Instance "_Controller" has been initialized
[2024-12-27 16:12:37.413227][INFO]: Instance "FrpcSettingController" has been created
[2024-12-27 16:12:37.417372][INFO]: Instance "FrpcSettingController" has been initialized
[2024-12-27 16:12:37.418409][INFO]: Instance "LauncherSettingLauncherController" has been created
[2024-12-27 16:12:37.418935][INFO]: Instance "LauncherSettingLauncherController" has been initialized
[2024-12-27 16:12:37.419978][INFO]: 
=== [DATA START] ===
[
  "0.51.3-6"
]
=== [DATA END] ===
[2024-12-27 16:12:37.420571][INFO]: Build windows platform arch list
[2024-12-27 16:14:01.821313][INFO]: OPEN DIALOG 914688617
[2024-12-27 16:14:06.620276][INFO]: Killing all process
[2024-12-27 16:14:06.621469][INFO]: All process killed
[2024-12-27 16:14:24.770364][INFO]: Instance "GetMaterialController" has been created
[2024-12-27 16:14:24.771371][INFO]: Instance "GetMaterialController" has been initialized
[2024-12-27 16:14:24.772801][INFO]: Instance "HomeController" has been created
[2024-12-27 16:14:24.772801][INFO]: Instance "HomeController" has been initialized
[2024-12-27 16:14:24.774307][INFO]: Instance "FrpcController" has been created
[2024-12-27 16:14:24.774307][INFO]: Instance "FrpcController" has been initialized
[2024-12-27 16:14:24.775312][INFO]: Instance "ConsoleController" has been created
[2024-12-27 16:14:24.775312][INFO]: Instance "ConsoleController" has been initialized
[2024-12-27 16:14:24.776312][INFO]: Instance "UserController" has been created
[2024-12-27 16:14:24.777312][INFO]: Instance "UserController" has been initialized
[2024-12-27 16:14:24.789097][ERROR]: PathNotFoundException: Cannot open file, path = 'C:\Users\qwert\AppData\Roaming\moe.muska.ami\nyanana/session.json' (OS Error: 系统找不到指定的文件。
, errno = 2)
Trace:
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#3      _File.readAsString (dart:io/file_impl.dart:621)
<asynchronous suspension>
#4      UserInfoStorage.read (package:nyalcf_core/storages/stores/user_info_storage.dart:26)
<asynchronous suspension>
#5      HomeController.load (package:nyalcf_ui/views/home.dart:163)
<asynchronous suspension>

[2024-12-27 16:14:27.118010][INFO]: Instance "_Controller" has been created
[2024-12-27 16:14:27.126949][INFO]: Instance "_Controller" has been initialized

**Comment by Muska-Ami** [comment]
暂时不清楚原因，我这边测试环境是正常的，晚点看看能不能复现

**Comment by Muska-Ami** [comment]
Maybe fix this issue: #224

**Comment by Suisuroru** [comment]
[run.log](https://github.com/user-attachments/files/18331053/run.log)
日志文件

**Comment by Muska-Ami** [comment]
貌似没有在日志中找到什么有效的信息，或许应该打开 DEBUG Logger 以获取更详细的日志

**Comment by Suisuroru** [comment]
那这个日志呢，已启用debug







&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Muska-Ami/NyaLCF"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Jan 7, 2025 06:50 PM
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
Subject:&nbsp;Re: [Muska-Ami/NyaLCF] [BUG]: 无法正常完成授权 (Issue #220)





 
貌似没有在日志中找到什么有效的信息，或许应该打开 DEBUG Logger 以获取更详细的日志

**Comment by Muska-Ami** [comment]
请不要通过邮件附件，GitHub 并不会一并上传附件

**Comment by Suisuroru** [comment]
已经对评论修正了

**Comment by Muska-Ami** [comment]
@Suisuroru 直接登录面板没有问题嘛？只看到了两个网络请求错误，没有找到什么其他有效的数据

**Comment by Suisuroru** [comment]
面板的登陆无异常，只有启动器的登陆存在问题，网页授权也能正常完成

**Comment by Muska-Ami** [comment]
@Suisuroru 删除数据目录下的 shared_preferences.json 重试一下试试

**Comment by Suisuroru** [comment]
删除后仍然无效，我将尝试使用QQ将PSR数据和我的本地数据发送给您，由于一些隐私数据，这些数据不应该在这里被公布







&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Muska-Ami/NyaLCF"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Jan 7, 2025 07:30 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Muska-Ami/NyaLCF] [BUG]: 无法正常完成授权 (Issue #220)





 
@Suisuroru 删除数据目录下的 shared_preferences.json 重试一下试试

**Comment by Muska-Ami** [comment]
此问题经排查为流量数值异常为 `INF` 导致，已超出设计范围，是一个上游 BUG，可行的解决方案：

- 重置账户流量

此问题将被关闭，因为并非启动器本身导致
