### ISSUE TITLE
macos没办法登录和下载

### ISSUE THREAD

**Issue by GuCheng114514** [Muska-Ami/NyaLCF#23]
![1327717b59393cf2be2daf7f2c0aa4a9](https://github.com/Muska-Ami/NyaLCF/assets/121870522/b9549145-573a-4c18-99c5-0fac3eca2f8d)
均在sudo模式下
登录报错：
```
2024-01-10 22:15:12.315 nyanana[4599:157304] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
flutter: Post login: *************
flutter: DioException [connection error]: The connection errored: Failed host lookup: 'api-v2.locyanfrp.cn' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'api-v2.locyanfrp.cn' (OS Error: nodename nor servname provided, or not known, errno = 8)
下载报错：
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      StatefulElement.state (package:flutter/src/widgets/framework.dart:5590)
#1      Element.findRootAncestorStateOfType (package:flutter/src/widgets/framework.dart:4832)
#2      Navigator.of (package:flutter/src/widgets/navigator.dart:2683)
#3      showDialog (package:flutter/src/material/dialog.dart:1417)
#4      FrpcDownloadTip.tip.<anonymous closure> (package:nyalcf/ui/model/FrpcDownloadTip.dart:28)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#23     _invoke1 (dart:ui/hooks.dart:328)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
```

**Comment by Muska-Ami** [comment]
Fixed by #24
