### ISSUE TITLE
隧道刷新不出来

### ISSUE THREAD

**Issue by GuCheng114514** [Muska-Ami/NyaLCF#27]
```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:382)
#1      ServicesBinding.instance (package:flutter/src/services/binding.dart:56)
#2      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:146)
#3      BasicMessageChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:192)
#4      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:206)
#5      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:38)
#6      PathProviderFoundation.getApplicationSupportPath (package:path_provider_foundation/path_provider_foundation.dart:35)
#7      getApplicationSupportDirectory (package:path_provider/path_provider.dart:78)
#8      FileIO._support_path (package:nyalcf/util/FileIO.dart:6)
#9      FileIO.support_path (package:nyalcf/util/FileIO.dart)
#10     FrpcManagerStorage._s_path (package:nyalcf/io/frpcManagerStorage.dart:9)
#11     SettingStorage.init (package:nyalcf/io/settingStorage.dart)
#12     main (package:nyalcf/main.dart:22)
#13     _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:382)
#1      ServicesBinding.instance (package:flutter/src/services/binding.dart:56)
#2      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:146)
#3      BasicMessageChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:192)
#4      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:206)
#5      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:38)
#6      PathProviderFoundation.getApplicationSupportPath (package:path_provider_foundation/path_provider_foundation.dart:35)
#7      getApplicationSupportDirectory (package:path_provider/path_provider.dart:78)
#8      FileIO._support_path (package:nyalcf/util/FileIO.dart:6)
#9      FileIO.support_path (package:nyalcf/util/FileIO.dart)
#10     FrpcManagerStorage._s_path (package:nyalcf/io/frpcManagerStorage.dart:9)
#11     SettingStorage.init (package:nyalcf/io/settingStorage.dart)
#12     main (package:nyalcf/main.dart:22)
#13     _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)


```

**Comment by Muska-Ami** [comment]
由于由同意愿意导致，故关闭此Issue，感谢反馈
